[package]
authors = ["Lakelezz <lakelezz@protonmail.ch>", "Icemic <bingfeng.web@gmail.com>"]
categories = ["api-bindings", "compression", "encoding", "multimedia::audio", "multimedia::encoding"]
description = "FFI-Binding to Opus, dynamically or statically linked for Windows and UNIX."
documentation = "https://docs.rs/audiopus_sys"
edition = "2018"
keywords = ["audio", "opus", "codec"]
license = "ISC"
name = "audiopus_sys"
readme = "README.md"
repository = "https://github.com/Icemic/audiopus_sys.git"
version = "0.2.1"

[features]
default = []
dynamic = []
generate_binding = ["bindgen"]
static = []

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
libm = "0.2"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
log = "0.4"
pkg-config = "0.3"

[build-dependencies.bindgen]
optional = true
version = "0.58"
